name: wallpaper
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  share:
  google_fonts:
  localstorage:
  staggered_grid_view_flutter:
  animate_gradient:
  cupertino_icons:
  fluttertoast:
  rflutter_alert:
  http:
  cached_network_image:
  flutter_cache_manager:
  image_gallery_saver:
  permission_handler:
  random_string:
  dio:
  url_launcher_web:
  url_launcher:
  ntp:
  intl:
  flutter_rating_bar:
  provider:
  flutter_wallpaper_manager:
  photo_view:
  get:
  google_mobile_ads:
  scroll_page_view:

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/draver/685681.png
  #   - images/a_dot_ham.jpeg


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
